# Generated by Django 2.2.12 on 2020-06-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField(blank=True)),
                ('imdburl', models.URLField()),
                ('addtowatchlist', models.BooleanField(default=False)),
                ('trailerurl', models.URLField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genre.Genre')),
            ],
        ),
    ]
