# Generated by Django 2.2.12 on 2020-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesgenre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
