# Generated by Django 2.2.12 on 2020-06-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesgenre', '0003_auto_20200608_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imagefull',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imagethumb',
        ),
    ]
