# Generated by Django 2.2.12 on 2020-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesgenre', '0004_auto_20200608_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imagefull',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='photos/full/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imagethumb',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='photos/thumb/'),
        ),
    ]
