# Generated by Django 2.2.12 on 2020-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imagethumb', models.ImageField(blank=True, default=False, null=True, upload_to='photos/thumb/')),
                ('imagefull', models.ImageField(blank=True, default=False, null=True, upload_to='photos/full/')),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(max_length=500)),
                ('unit1', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('unit2', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('unit3', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('book1', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('bookurl1', models.URLField(blank=True, default=False, null=True)),
                ('book2', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('bookurl2', models.URLField(blank=True, default=False, null=True)),
                ('book3', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('bookurl3', models.URLField(blank=True, default=False, null=True)),
                ('quiz', models.URLField()),
                ('video', models.URLField()),
            ],
        ),
    ]
