# Generated by Django 2.2.12 on 2020-06-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='photo',
        ),
    ]
